#!/usr/bin/env python
import os
import sys
import glob

libname = "{{cookiecutter.project_name}}"

localEnv = Environment(tools=["default"], PLATFORM="")

customs = ["custom.py"]
customs = [os.path.abspath(path) for path in customs]

opts = Variables(customs, ARGUMENTS)
opts.Update(localEnv)

Help(opts.GenerateHelpText(localEnv))

env = localEnv.Clone()

if not (os.path.isdir("godot-cpp") and os.listdir("godot-cpp")):
    print("""godot-cpp is not available within this folder, as Git submodules haven't been initialized.
Run the following command to download godot-cpp:

    git submodule update --init --recursive""")
    sys.exit(1)

env = SConscript("godot-cpp/SConstruct", {"env": env, "customs": customs})

if "dev_build" in ARGUMENTS and ARGUMENTS["dev_build"] == "yes" or "dev_build" in ARGUMENTS and ARGUMENTS["dev_build"] == True or "server" in ARGUMENTS:
    env.Append(CPPDEFINES=["SERVER"])
if "dev_build" in ARGUMENTS and ARGUMENTS["dev_build"] == "yes" or "dev_build" in ARGUMENTS and ARGUMENTS["dev_build"] == True or "server" not in ARGUMENTS:
    env.Append(CPPDEFINES=["CLIENT"])
if env.get("is_msvc", False):
    env["CXXFLAGS"] = [f for f in env["CXXFLAGS"] if f != "/std:c++17"]
    env.Append(CXXFLAGS=["/std:c++20"])
else:
    env["CXXFLAGS"] = [f for f in env["CXXFLAGS"] if f != "-std=c++17"]
    env.Append(CXXFLAGS=["-std=c++20"])

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

PATH_DELIMITER = ";!$"
def recurse_public(path: str, folder: str) -> str:
    out_value: str = ""
    abs_path = f"{path}/{folder}"
    if not os.path.isdir(abs_path):
        #print("not folder: ", abs_path)
        return ""
    
    public_folder = f"{abs_path}/public"
    if os.path.isdir(public_folder):
        #print("found public: ", public_folder)
        out_value = public_folder
    
    for new_folder in os.listdir(abs_path):
        if new_folder != public_folder:
            v = recurse_public(abs_path, new_folder)
            if v != "":
                out_value = f"{out_value}{PATH_DELIMITER}{v}"
    
    return out_value

cpp_paths = "src/"
for module in os.listdir("src/modules"):
    cpp_paths = f"{cpp_paths}{PATH_DELIMITER}{recurse_public("src/modules", module)}"

cpp_paths = list(filter(lambda s: s != "", cpp_paths.split(PATH_DELIMITER)))
env.Append(CPPPATH=cpp_paths)

sources = [File(f) for f in glob.glob("src/**/*.cpp", recursive=True)]

# .dev doesn't inhibit compatibility, so we don't need to key it.
# .universal just means "compatible with all relevant arches" so we don't need to key it.
suffix = env['suffix'].replace(".dev", "").replace(".universal", "")

lib_filename = "{}{}{}{}".format(env.subst('$SHLIBPREFIX'), libname, suffix, env.subst('$SHLIBSUFFIX'))

library = env.SharedLibrary(
    "bin/{}/{}".format(env['platform'], lib_filename),
    source=sources,
)

copy = env.Install("playground/bin/{}/".format(env["platform"]), library)

default_args = [library, copy]
Default(*default_args)